spring:
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672
  mail:
    host: smtp.qq.com
    username: 272685110@qq.com
    password: password
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8812}/eureka/
server:
  port: 8008
aliyun:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  regionId: cn-hangzhou
  endpointName: cn-hangzhou
  accessKeyId: accessKeyId
  accessKeySecret: accessKeySecret
